### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fthamura** [harrypujianto/vtweb-opencart-2.0#4]
Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in

**Comment by harrypujianto** [comment]
could you tell me how to produce this error?

**Comment by fthamura** [comment]
i just extract and upload to the public_hub, with root of admin/system etc..

and i can see the module with veritrans logo in module-payment.. when click "edit" after enable, show this error.

**Comment by harrypujianto** [comment]
do u use this module on OC 1.5 by any chance? it's works for me on OC 2.0,2.1 & 2.2

**Comment by fthamura** [comment]
opencart 2.2 here..

**Comment by fthamura** [comment]
i try to reupload.. work now..
