### ISSUE TITLE
dapat error

### ISSUE THREAD

**Issue by fthamura** [harrypujianto/vtweb-opencart-2.0#8]
saya dapat error ini

Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/veritrans.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentVeritrans::$data has no effect in /home/smkholdi/public_html/mm/admin/controller/payment/verit

**Comment by harrypujianto** [comment]
Ini terjadinya pas kapan pak? sudah solved kah?

**Comment by fthamura** [comment]
Sudah..
